apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
  labels:
    app: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo-container
          image: ultralytics/ultralytics:latest
          command: ["yolo"]
          args: [
            "predict",
            "model=yolo11n.pt",
            "source=/home/mounts/input/sipping_coffee.jpg",
            "project=/home/mounts/output"
          ]
          volumeMounts:
            - mountPath: "/home/mounts"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yolo-pvc
