apiVersion: v1
kind: PersistentVolume
metadata:
  name: yolo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi #mebibyte
  accessModes:
    - ReadWriteOnce # the volume can be mounted as Read-Write by only one node at a time
  hostPath:
    path: /mnt/data #path in the filesystem of the host (actually the minikube vm)
